POST http://localhost:8080/api/tournaments
Content-Type: application/json

{
  "organizer":"ESL",
  "city":"Lhota",
  "year":"2015"
}

###201
PUT http://localhost:8080/api/tournaments/2
Content-Type: application/json

{
  "organizer":"ESL",
  "city":"Praha",
  "year":"2017"
}

###204
POST http://localhost:8080/api/rosters
Content-Type: application/json

{
  "name":"SK"
}
###201
PUT http://localhost:8080/api/rosters/2
Content-Type: application/json

{
  "name":"Brambory"
}

###204
GET http://localhost:8080/api/tournaments

###200
GET http://localhost:8080/api/rosters

###200
GET http://localhost:8080/api/tournaments/1/rosters/

###200
GET http://localhost:8080/api/rosters/3/tournaments/

###200
PUT http://localhost:8080/api/tournaments/1/rosters/3

###204
PUT http://localhost:8080/api/rosters/3/tournaments/2

###200
PUT http://localhost:8080/api/tournaments/1/rosters/4

###204
DELETE http://localhost:8080/api/tournaments/1/rosters/4

###204
DELETE http://localhost:8080/api/rosters/3/tournaments/2

###204